### ISSUE TITLE
Doesn't show progress bar on refresh of page even when fields have value prefilled

### ISSUE THREAD

**Issue by ramansharma89** [seapage/FormProgressBar#3]
Hi,

I'm using this plugin in one of my project. It works fine but when I refresh the page and the fields already have the values filled in, the progress bar doesn't take that into account. But once I try to refill the values it works fine.

Please help.

**Comment by wokayme** [comment]
Fixed in commit last commit: https://github.com/seapage/FormProgressBar/commit/39de34439367b619814c2d03d674ec4428eac34e
